### ISSUE TITLE
Error if the speaker is not found

### ISSUE THREAD

**Issue by chettai** [macbury/ha_samsung_multi_room#2]
If the speaker is not reachable, Home-Assistant throws the following error in the log. 
Is it possible to handle this situation? My speaker is connected to a smart plug and has only power when it is in use.
--
Log:
```
2019-02-05 21:53:22 WARNING (MainThread) [homeassistant.loader] You are using a custom component for customizer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-05 21:53:33 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform samsung_multi_room is taking over 10 seconds.
2019-02-05 21:53:33 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform samsung_multi_room
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x705e63b0>, 'Connection to 192.168.1.107 timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.107', port=55001): Max retries exceeded with url: /UIC?cmd=%3Cname%3EGetFunc%3C%2Fname%3E (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x705e63b0>, 'Connection to 192.168.1.107 timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/samsung_multi_room.py", line 175, in setup_platform
    add_devices([MultiRoomDevice(name, max_volume, api)], True)
  File "/config/custom_components/media_player/samsung_multi_room.py", line 115, in __init__
    self.update()
  File "/config/custom_components/media_player/samsung_multi_room.py", line 160, in update
    self._current_source = self.api.get_source()
  File "/config/custom_components/media_player/samsung_multi_room.py", line 101, in get_source
    return self._exec_get('GetFunc', 'function')
  File "/config/custom_components/media_player/samsung_multi_room.py", line 69, in _exec_get
    return self._exec_cmd('<name>{0}</name>'.format(action), key_to_extract)
  File "/config/custom_components/media_player/samsung_multi_room.py", line 64, in _exec_cmd
    req = requests.get(url, timeout=10)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.1.107', port=55001): Max retries exceeded with url: /UIC?cmd=%3Cname%3EGetFunc%3C%2Fname%3E (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x705e63b0>, 'Connection to 192.168.1.107 timed out. (connect timeout=10)'))

```

**Comment by macbury** [comment]
I have new version for this component that lie in other private repo, that has fixed this issue. I will try to merge it today.

**Comment by macbury** [comment]
hey @chettai, I upgraded media player to use new async api for fetching information from soundbar.

**Comment by chettai** [comment]
Hi macbury

I still get errors. Perhaps I am missing something here.
```
2019-02-11 12:19:53 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.samsung_m7 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1879, in create_connection
  File "uvloop/loop.pyx", line 1858, in uvloop.loop.Loop.create_connection
OSError: [Errno 113] Host is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/config/custom_components/media_player/samsung_multi_room.py", line 178, in async_update
    self._current_source = await self.api.get_source()
  File "/config/custom_components/media_player/samsung_multi_room.py", line 118, in get_source
    return await self._exec_get('GetFunc', 'function')
  File "/config/custom_components/media_player/samsung_multi_room.py", line 86, in _exec_get
    return await self._exec_cmd('<name>{0}</name>'.format(action), key_to_extract)
  File "/config/custom_components/media_player/samsung_multi_room.py", line 76, in _exec_cmd
    response = await self.session.get(url)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.107:55001 ssl:None [Host is unreachable]
```
